---
version: 1
disable_existing_loggers: False
formatters:
    verbose:
        format: "%(levelname)s %(asctime)s %(module)s - %(message)s"
    simple:
        format: '%(levelname)s %(message)s'

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: verbose
        filename: SPLyse.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: verbose
        filename: SPLyse.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: verbose
        filename: SPLyse.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
    null:
        class: logging.NullHandler

loggers:
    SPLyse:
        level: DEBUG
        handlers: [debug_file_handler]
        propagate: False
...